# Configuracion de correo electronico (Gmail - SSL Directo para Java 8)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.ssl.enable=true
mail.smtp.starttls.enable=false
mail.smtp.ssl.trust=smtp.gmail.com
mail.user=guillermo.andres.vallejos1979@gmail.com
mail.password=xwlcvxulwqvsgvpw
